/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* src = "mult.v:1" *)
module mux(select, d, q);
  (* src = "mult.v:4" *)
  input [3:0] d;
  (* src = "mult.v:5" *)
  output q;
  (* src = "mult.v:3" *)
  input [1:0] select;
  (* src = "mult.v:11" *)
  \$shiftx  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd4),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd2),
    .Y_WIDTH(32'd1)
  ) _0_ (
    .A(d),
    .B(select),
    .Y(q)
  );
endmodule
