/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 5.4.0-6ubuntu1~16.04.4 -O2 -fstack-protector-strong -fPIC -Os) */

(* src = "fulladder.v:4" *)
module fulladder(sum, c1, a, b, c);
  (* src = "fulladder.v:7" *)
  input a;
  (* src = "fulladder.v:7" *)
  input b;
  (* src = "fulladder.v:7" *)
  input c;
  (* src = "fulladder.v:6" *)
  output c1;
  (* src = "fulladder.v:8" *)
  wire c_1;
  (* src = "fulladder.v:8" *)
  wire c_2;
  (* src = "fulladder.v:6" *)
  output sum;
  assign c1 = c_1 |(* src = "fulladder.v:14" *)  c_2;
endmodule

(* src = "halfadder.v:1" *)
module halfadder(sum, c, a, b);
  (* src = "halfadder.v:4" *)
  input a;
  (* src = "halfadder.v:4" *)
  input b;
  (* src = "halfadder.v:3" *)
  output c;
  (* src = "halfadder.v:3" *)
  output sum;
  assign sum = a ^(* src = "halfadder.v:6" *)  b;
  assign c = a &(* src = "halfadder.v:7" *)  b;
endmodule
